name: 002-DEBUG

on:
  schedule:
  - cron: '37 13,15,17,19,21,23,1,3,5,7 * * *'  #5-7-9-11-13-15-17-19-21&&&
  workflow_dispatch:
    分支:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet
      - name: Install dependencies
        run: pip install replace
      - name: Install dependencies
        run: pip install input
     

      - name: Run iptv
        run: python ${{ github.workspace }}/ZUZU-PY/#github-DEBUG.py
      
        

      - name: 提交更改
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit *.txt -m "Add generated file"
          #git pull --rebase
          git push -f
